import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

/// Small, dependency-free localization layer for the desktop UI.
///
/// The website and app deliberately share the same eight language codes. Text
/// that has not been localized yet falls back to English instead of rendering
/// an empty label.
class AbyssLAppLocalizations {
  const AbyssLAppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[
    Locale('en'),
    Locale('de'),
    Locale('fr'),
    Locale('es'),
    Locale('pt'),
    Locale('it'),
    Locale('nl'),
    Locale('hr'),
  ];

  static const delegate = _AbyssLAppLocalizationsDelegate();

  static AbyssLAppLocalizations of(BuildContext context) =>
      Localizations.of<AbyssLAppLocalizations>(
        context,
        AbyssLAppLocalizations,
      ) ??
      const AbyssLAppLocalizations(Locale('en'));

  String text(String value) =>
      _copy[locale.languageCode]?[value] ?? _copy['en']?[value] ?? value;

  /// Used by localization coverage tests to prevent English UI fragments from
  /// silently reappearing in a supported language.
  bool hasTranslation(String value) =>
      locale.languageCode == 'en' ||
      (_copy[locale.languageCode]?.containsKey(value) ?? false);

  static const _copy = <String, Map<String, String>>{
    'en': {},
    'de': {
      'System default': 'Systemstandard',
      'English': 'Englisch',
      'French': 'Französisch',
      'Spanish': 'Spanisch',
      'Portuguese': 'Portugiesisch',
      'Italian': 'Italienisch',
      'Dutch': 'Niederländisch',
      'Croatian': 'Kroatisch',
      'Translate': 'Übersetzen',
      'Correction': 'Korrektur',
      'Documents': 'Dokumente',
      'Settings': 'Einstellungen',
      'Direct instruction': 'Direkte Anweisung',
      'Provide context or instructions for translation…':
          'Kontext oder Anweisungen für die Übersetzung angeben…',
      'Type or paste your source text here…':
          'Quelltext hier eingeben oder einfügen…',
      'Translation': 'Übersetzung',
      'Your translation will appear here…': 'Deine Übersetzung erscheint hier…',
      'Source': 'Quelle',
      'Target': 'Ziel',
      'Automatic': 'Automatisch',
      'Copy': 'Kopieren',
      'More alternatives': 'Weitere Alternativen',
      'Generate more alternatives': 'Weitere Alternativen erzeugen',
      'Generate more': 'Weitere erzeugen',
      'Alternative instruction (optional)':
          'Anweisung für Alternativen (optional)',
      'Alternatives': 'Alternativen',
      'Suggestions for the full translation':
          'Vorschläge für die gesamte Übersetzung',
      'Alternatives for the full translation':
          'Alternativen für die gesamte Übersetzung',
      'Alternatives for': 'Alternativen für',
      'Auto-translate': 'Automatisch übersetzen',
      'Clear': 'Leeren',
      'Correct': 'Korrigieren',
      'Correct text': 'Text korrigieren',
      'Rewrite': 'Umschreiben',
      'Input': 'Eingabe',
      'Corrected / rewritten text': 'Korrigierter / umgeschriebener Text',
      'Rewrite style': 'Umschreibstil',
      'Standard': 'Standard',
      'Add files': 'Dateien hinzufügen',
      'Add folder': 'Ordner hinzufügen',
      'Output folder': 'Ausgabeordner',
      'Process': 'Verarbeiten',
      'Drop files or folders here.': 'Dateien oder Ordner hier ablegen.',
      'Results appear here.': 'Ergebnisse erscheinen hier.',
      'General': 'Allgemein',
      'AI Providers': 'KI-Anbieter',
      'About': 'Über',
      'Appearance': 'Darstellung',
      'Choose how AbyssL looks on this device.':
          'Lege fest, wie AbyssL auf diesem Gerät aussieht.',
      'Application language': 'App-Sprache',
      'Language': 'Sprache',
      'Follow the macOS language or choose an app language.':
          'macOS-Sprache übernehmen oder eine App-Sprache wählen.',
      'Default provider': 'Standardanbieter',
      'Editor and capture': 'Editor und Erfassung',
      'Provider': 'Anbieter',
      'Configuration': 'Konfiguration',
      'Edit endpoints and models under AI Providers':
          'Endpunkte und Modelle unter KI-Anbieter bearbeiten',
      'Theme': 'Farbschema',
      'Translation style': 'Übersetzungsstil',
      'System': 'System',
      'Light': 'Hell',
      'Dark': 'Dunkel',
      'Save': 'Speichern',
      'Cancel': 'Abbrechen',
      'OpenAI-compatible': 'OpenAI-kompatibel',
      'Anthropic-compatible': 'Anthropic-kompatibel',
      'Local OpenAI-compatible': 'Lokal OpenAI-kompatibel',
      'Base URL': 'Basis-URL',
      'Model ID': 'Modell-ID',
      'Timeout seconds': 'Timeout in Sekunden',
      'Authentication': 'Authentifizierung',
      'API key': 'API-Schlüssel',
      'Load models': 'Modelle laden',
      'Detect Local': 'Lokales Modell erkennen',
      'Test connection': 'Verbindung testen',
      'Reasoning': 'Schlussfolgern',
      'Refresh': 'Aktualisieren',
      'Reasoning enabled': 'Schlussfolgern aktiviert',
      'Check for updates': 'Nach Updates suchen',
      'Command': 'Befehl',
      'Type a command or press ⌘K': 'Befehl eingeben oder ⌘K drücken',
      'Style': 'Stil',
      'Custom': 'Benutzerdefiniert',
      'Register': 'Sprachregister',
      'Complexity': 'Komplexität',
      'Spelling': 'Rechtschreibung',
      'Reset to defaults': 'Auf Standardwerte zurücksetzen',
      'Neutral': 'Neutral',
      'Formal': 'Formell',
      'Informal': 'Informell',
      'Technical': 'Technisch',
      'Plain': 'Einfach',
      'Preserve': 'Beibehalten',
      'Fix source': 'Quelltext korrigieren',
      'Fix target': 'Zieltext korrigieren',
      'English (US)': 'Englisch (USA)',
      'English (UK)': 'Englisch (GB)',
      'German': 'Deutsch',
      'Polish': 'Polnisch',
      'Russian': 'Russisch',
      'Japanese': 'Japanisch',
      'Korean': 'Koreanisch',
      'Chinese Simplified': 'Chinesisch (vereinfacht)',
      'Chinese Traditional': 'Chinesisch (traditionell)',
      'Swap source and target languages': 'Quell- und Zielsprache tauschen',
      'Choose a fixed source language to swap languages':
          'Zum Tauschen eine feste Quellsprache wählen',
      'Ready': 'Bereit',
      'Translated': 'Übersetzt',
      'Copy translation': 'Übersetzung kopieren',
      'Clear source and translation': 'Quelle und Übersetzung leeren',
      'Translate automatically after source changes':
          'Nach Änderungen am Quelltext automatisch übersetzen',
      'Manual translation only': 'Nur manuell übersetzen',
      'Close style options': 'Stiloptionen schließen',
      'Correction instruction': 'Korrekturanweisung',
      'Describe how the text should be corrected or rewritten…':
          'Beschreibe, wie der Text korrigiert oder umgeschrieben werden soll…',
      'Type or paste the text you want to improve…':
          'Den zu verbessernden Text hier eingeben oder einfügen…',
      'characters': 'Zeichen',
      'Clear input and correction': 'Eingabe und Korrektur leeren',
      'Copy result': 'Ergebnis kopieren',
      'The corrected or rewritten text will appear here…':
          'Der korrigierte oder umgeschriebene Text erscheint hier…',
      'Concise': 'Prägnant',
      'Ultra Short': 'Ultrakurz',
      'No output folder selected': 'Kein Ausgabeordner ausgewählt',
      'queued': 'in Warteschlange',
      'Optional instruction for all documents…':
          'Optionale Anweisung für alle Dokumente…',
      'Export': 'Export',
      'Processing results': 'Verarbeitungsergebnisse',
      'Results appear here': 'Ergebnisse erscheinen hier',
      'Remove': 'Entfernen',
      'error': 'Fehler',
      'errors': 'Fehler',
      'Local LLM models found. Select one in Settings.':
          'Lokale LLM-Modelle gefunden. Bitte eines in den Einstellungen auswählen.',
      'Local LLM auto detection failed':
          'Automatische Erkennung des lokalen LLM fehlgeschlagen',
      'Detected local model': 'Lokales Modell erkannt',
      'Reasoning options': 'Reasoning-Optionen',
      'Reasoning metadata unavailable': 'Reasoning-Metadaten nicht verfügbar',
      'Request cancelled.': 'Anfrage abgebrochen.',
      'Cancelling request…': 'Anfrage wird abgebrochen…',
      'Auto-translate setting could not be saved':
          'Einstellung für automatisches Übersetzen konnte nicht gespeichert werden',
      'Unknown command. Try Translate, Correct, Rewrite, Documents, or Settings.':
          'Unbekannter Befehl. Versuche Übersetzen, Korrigieren, Umschreiben, Dokumente oder Einstellungen.',
      'macOS capture adapter is active.': 'Die macOS-Erfassung ist aktiv.',
      'macOS requires Accessibility/Input Monitoring permission for global capture.':
          'macOS benötigt für die globale Erfassung die Berechtigung für Bedienungshilfen/Eingabeüberwachung.',
      'CONFIGURATION': 'KONFIGURATION',
      'Changes are stored locally.': 'Änderungen werden lokal gespeichert.',
      'Select the service used for new requests.':
          'Wähle den Dienst für neue Anfragen.',
      'Tune text size and the global capture shortcut.':
          'Textgröße und globales Erfassungskürzel anpassen.',
      'Editor font size': 'Editor-Schriftgröße',
      'Font': 'Schriftgröße',
      'Capture modifier': 'Erfassungs-Modifikatortaste',
      'Capture key': 'Erfassungstaste',
      'Connect to an OpenAI-compatible model server on your network.':
          'Mit einem OpenAI-kompatiblen Modellserver im Netzwerk verbinden.',
      'Configure any service that implements this compatible API format.':
          'Jeden Dienst konfigurieren, der dieses kompatible API-Format unterstützt.',
      'Include the API path, for example /v1.':
          'API-Pfad einschließen, zum Beispiel /v1.',
      'Bearer token': 'Bearer-Token',
      'No authentication': 'Keine Authentifizierung',
      'Stored in the operating system keychain.':
          'Wird im Schlüsselbund des Betriebssystems gespeichert.',
      'Anthropic version header': 'Anthropic-Versionsheader',
      'Default': 'Standard',
      'Available models': 'Verfügbare Modelle',
      'Map model-specific reasoning values.':
          'Modellspezifische Reasoning-Werte zuordnen.',
      'Reasoning value ON': 'Reasoning-Wert EIN',
      'Reasoning value OFF': 'Reasoning-Wert AUS',
      'None': 'Keine',
      'Off': 'Aus',
      'On': 'Ein',
      'Low': 'Niedrig',
      'Medium': 'Mittel',
      'High': 'Hoch',
      'Connection successful.': 'Verbindung erfolgreich.',
      'No local models were returned by /api/v1/models or /v1/models.':
          'Über /api/v1/models oder /v1/models wurden keine lokalen Modelle zurückgegeben.',
      'Local models found': 'Lokale Modelle gefunden',
      'Select one or enter the model name manually.':
          'Wähle eines aus oder gib den Modellnamen manuell ein.',
      'No models were returned. Enter a model ID manually.':
          'Es wurden keine Modelle zurückgegeben. Gib eine Modell-ID manuell ein.',
      'Models found': 'Modelle gefunden',
      'About AbyssL': 'Über AbyssL',
      'Application details, project website, and updates.':
          'App-Details, Projektwebsite und Updates.',
      'AbyssL logo': 'AbyssL-Logo',
      'Developed by Daniel Mengel': 'Entwickelt von Daniel Mengel',
      'Version loading…': 'Version wird geladen…',
      'Version': 'Version',
      'unavailable': 'nicht verfügbar',
      'Software updates': 'Softwareupdates',
      'Check the latest published GitHub release and install signed macOS updates securely.':
          'Das neueste GitHub-Release prüfen und signierte macOS-Updates sicher installieren.',
      'Check GitHub to see whether a newer release is available.':
          'Auf GitHub prüfen, ob ein neueres Release verfügbar ist.',
      'Installed version': 'Installierte Version',
      'Check GitHub for updates.': 'Auf GitHub nach Updates suchen.',
      'Could not read the installed app version':
          'Die installierte App-Version konnte nicht gelesen werden',
      'Checking the latest published GitHub release…':
          'Das neueste veröffentlichte GitHub-Release wird geprüft…',
      'No AbyssL release has been published on GitHub yet.':
          'Auf GitHub wurde noch kein AbyssL-Release veröffentlicht.',
      'is the newest published version.':
          'ist die neueste veröffentlichte Version.',
      'is available. The signed update can be downloaded and installed automatically.':
          'ist verfügbar. Das signierte Update kann automatisch heruntergeladen und installiert werden.',
      'is published, but its signed macOS update files are not available yet.':
          'ist veröffentlicht, aber die signierten macOS-Updatedateien sind noch nicht verfügbar.',
      'Opening the secure macOS updater. It will verify, install, and relaunch AbyssL.':
          'Der sichere macOS-Updater wird geöffnet. Er prüft und installiert das Update und startet AbyssL neu.',
      'Download and install…': 'Herunterladen und installieren…',
      'Open GitHub release': 'GitHub-Release öffnen',
      'Add at least one file or folder.':
          'Füge mindestens eine Datei oder einen Ordner hinzu.',
      'Choose an output folder.': 'Wähle einen Ausgabeordner.',
      'Processed': 'Verarbeitet',
      'Unsupported file type.': 'Nicht unterstützter Dateityp.',
      'ODT requires LibreOffice soffice; no safe local converter was found.':
          'ODT benötigt LibreOffice soffice; es wurde kein geeigneter lokaler Konverter gefunden.',
      'Pages files are not supported by the cross-platform document path.':
          'Pages-Dateien werden von der plattformübergreifenden Dokumentverarbeitung nicht unterstützt.',
      'Numbers files are not supported by the cross-platform document path.':
          'Numbers-Dateien werden von der plattformübergreifenden Dokumentverarbeitung nicht unterstützt.',
      'PDF text extraction is unavailable in this build. On macOS, rebuild and restart AbyssL to enable its built-in PDF reader. On other platforms, install Poppler (pdftotext) or MuPDF (mutool) and make it available on PATH. Scanned PDFs additionally require OCR.':
          'Die PDF-Texterkennung ist in diesem Build nicht verfügbar. Erstelle AbyssL unter macOS neu und starte die App erneut, um den integrierten PDF-Reader zu aktivieren. Installiere auf anderen Plattformen Poppler (pdftotext) oder MuPDF (mutool) und stelle das Programm über PATH bereit. Eingescannte PDFs benötigen zusätzlich OCR.',
      'PDF text extraction failed.': 'PDF-Textextraktion fehlgeschlagen.',
      'Native PDF extraction failed.':
          'Native PDF-Textextraktion fehlgeschlagen.',
      'Scanned PDFs without extractable text are not supported.':
          'Eingescannte PDFs ohne extrahierbaren Text werden nicht unterstützt.',
      'DOCX document.xml was not found.':
          'DOCX-Datei document.xml wurde nicht gefunden.',
      'Document is empty.': 'Das Dokument ist leer.',
      'Spreadsheet is empty.': 'Die Tabelle ist leer.',
      'XLSX workbook.xml was not found.':
          'XLSX-Datei workbook.xml wurde nicht gefunden.',
      'XLSX worksheet XML was not found.':
          'XLSX-Arbeitsblatt-XML wurde nicht gefunden.',
      'ODT conversion failed.': 'ODT-Konvertierung fehlgeschlagen.',
      'ODT conversion did not produce a text file.':
          'Die ODT-Konvertierung hat keine Textdatei erzeugt.',
      'ODT export failed.': 'ODT-Export fehlgeschlagen.',
      'LibreOffice did not produce an ODT file.':
          'LibreOffice hat keine ODT-Datei erzeugt.',
      'Pages export is not supported by the cross-platform document path.':
          'Der Pages-Export wird von der plattformübergreifenden Dokumentverarbeitung nicht unterstützt.',
      'Numbers export is not supported by the cross-platform document path.':
          'Der Numbers-Export wird von der plattformübergreifenden Dokumentverarbeitung nicht unterstützt.',
      'Export format is unavailable on this system.':
          'Das Exportformat ist auf diesem System nicht verfügbar.',
    },
    'fr': {
      'System default': 'Par défaut du système',
      'Translate': 'Traduire',
      'Correction': 'Correction',
      'Documents': 'Documents',
      'Settings': 'Réglages',
      'Direct instruction': 'Instruction directe',
      'Translation': 'Traduction',
      'Source': 'Source',
      'Target': 'Cible',
      'Automatic': 'Automatique',
      'Copy': 'Copier',
      'Alternatives': 'Alternatives',
      'More alternatives': 'Plus de variantes',
      'Generate more': 'Générer plus',
      'Suggestions for the full translation':
          'Suggestions pour toute la traduction',
      'Alternatives for the full translation':
          'Variantes pour toute la traduction',
      'Alternatives for': 'Variantes pour',
      'Auto-translate': 'Traduction automatique',
      'Clear': 'Effacer',
      'Correct': 'Corriger',
      'Rewrite': 'Réécrire',
      'General': 'Général',
      'AI Providers': 'Fournisseurs IA',
      'About': 'À propos',
      'Appearance': 'Apparence',
      'Application language': "Langue de l’application",
      'Language': 'Langue',
      'Theme': 'Thème',
      'System': 'Système',
      'Light': 'Clair',
      'Dark': 'Sombre',
      'Save': 'Enregistrer',
      'Cancel': 'Annuler',
      'Add files': 'Ajouter des fichiers',
      'Add folder': 'Ajouter un dossier',
      'Output folder': 'Dossier de sortie',
      'Process': 'Traiter',
      'Test connection': 'Tester la connexion',
      'Command': 'Commande',
      'Type a command or press ⌘K': 'Saisissez une commande ou appuyez sur ⌘K',
      'Style': 'Style',
      'Custom': 'Personnalisé',
      'Register': 'Registre',
      'Complexity': 'Complexité',
      'Spelling': 'Orthographe',
      'Reset to defaults': 'Rétablir les valeurs par défaut',
      'Neutral': 'Neutre',
      'Formal': 'Formel',
      'Informal': 'Informel',
      'Technical': 'Technique',
      'Plain': 'Simple',
      'Preserve': 'Conserver',
      'Fix source': 'Corriger la source',
      'Fix target': 'Corriger la cible',
      'English (US)': 'Anglais (États-Unis)',
      'English (UK)': 'Anglais (Royaume-Uni)',
      'German': 'Allemand',
      'French': 'Français',
      'Spanish': 'Espagnol',
      'Italian': 'Italien',
      'Portuguese': 'Portugais',
      'Dutch': 'Néerlandais',
      'Polish': 'Polonais',
      'Russian': 'Russe',
      'Japanese': 'Japonais',
      'Korean': 'Coréen',
      'Chinese Simplified': 'Chinois simplifié',
      'Chinese Traditional': 'Chinois traditionnel',
      'Swap source and target languages':
          'Intervertir les langues source et cible',
      'Choose a fixed source language to swap languages':
          'Choisissez une langue source fixe pour intervertir les langues',
      'Ready': 'Prêt',
      'Translated': 'Traduit',
      'Copy translation': 'Copier la traduction',
      'Clear source and translation': 'Effacer la source et la traduction',
      'Translate automatically after source changes':
          'Traduire automatiquement après modification de la source',
      'Manual translation only': 'Traduction manuelle uniquement',
      'Close style options': 'Fermer les options de style',
      'Correction instruction': 'Instruction de correction',
      'Describe how the text should be corrected or rewritten…':
          'Décrivez comment le texte doit être corrigé ou reformulé…',
      'Type or paste the text you want to improve…':
          'Saisissez ou collez le texte à améliorer…',
      'characters': 'caractères',
      'Clear input and correction': 'Effacer la saisie et la correction',
      'Copy result': 'Copier le résultat',
      'The corrected or rewritten text will appear here…':
          'Le texte corrigé ou reformulé apparaîtra ici…',
      'Concise': 'Concis',
      'Standard': 'Standard',
      'Ultra Short': 'Ultra court',
      'No output folder selected': 'Aucun dossier de sortie sélectionné',
      'queued': 'en attente',
      'Optional instruction for all documents…':
          'Instruction facultative pour tous les documents…',
      'Export': 'Exportation',
      'Processing results': 'Résultats du traitement',
      'Results appear here': 'Les résultats apparaissent ici',
      'Results appear here.': 'Les résultats apparaissent ici.',
      'Drop files or folders here.': 'Déposez les fichiers ou dossiers ici.',
      'Remove': 'Supprimer',
      'error': 'erreur',
      'errors': 'erreurs',
      'Detected local model': 'Modèle local détecté',
      'Reasoning options': 'Options de raisonnement',
      'Reasoning metadata unavailable':
          'Métadonnées de raisonnement indisponibles',
      'Request cancelled.': 'Requête annulée.',
      'Cancelling request…': 'Annulation de la requête…',
      'CONFIGURATION': 'CONFIGURATION',
      'Changes are stored locally.':
          'Les modifications sont enregistrées localement.',
      'Choose how AbyssL looks on this device.':
          'Choisissez l’apparence d’AbyssL sur cet appareil.',
      'Follow the macOS language or choose an app language.':
          'Suivez la langue de macOS ou choisissez la langue de l’application.',
      'Default provider': 'Fournisseur par défaut',
      'Select the service used for new requests.':
          'Sélectionnez le service utilisé pour les nouvelles requêtes.',
      'Provider': 'Fournisseur',
      'Configuration': 'Configuration',
      'Edit endpoints and models under AI Providers':
          'Modifiez les points d’accès et les modèles dans Fournisseurs IA',
      'Editor and capture': 'Éditeur et capture',
      'Tune text size and the global capture shortcut.':
          'Réglez la taille du texte et le raccourci de capture global.',
      'Editor font size': 'Taille de police de l’éditeur',
      'Font': 'Police',
      'Capture modifier': 'Touche modificatrice de capture',
      'Capture key': 'Touche de capture',
      'Base URL': 'URL de base',
      'Model ID': 'Identifiant du modèle',
      'Timeout seconds': 'Délai en secondes',
      'Authentication': 'Authentification',
      'API key': 'Clé API',
      'Include the API path, for example /v1.':
          'Incluez le chemin de l’API, par exemple /v1.',
      'Bearer token': 'Jeton Bearer',
      'No authentication': 'Aucune authentification',
      'Stored in the operating system keychain.':
          'Enregistrée dans le trousseau du système.',
      'Anthropic version header': 'En-tête de version Anthropic',
      'Default': 'Par défaut',
      'Available models': 'Modèles disponibles',
      'Load models': 'Charger les modèles',
      'Detect Local': 'Détecter en local',
      'Reasoning': 'Raisonnement',
      'Map model-specific reasoning values.':
          'Associez les valeurs de raisonnement propres au modèle.',
      'Reasoning value ON': 'Valeur de raisonnement ACTIVÉ',
      'Reasoning value OFF': 'Valeur de raisonnement DÉSACTIVÉ',
      'Reasoning enabled': 'Raisonnement activé',
      'Refresh': 'Actualiser',
      'None': 'Aucun',
      'Off': 'Désactivé',
      'On': 'Activé',
      'Low': 'Faible',
      'Medium': 'Moyen',
      'High': 'Élevé',
      'Connection successful.': 'Connexion réussie.',
      'About AbyssL': 'À propos d’AbyssL',
      'Application details, project website, and updates.':
          'Détails de l’application, site du projet et mises à jour.',
      'Developed by Daniel Mengel': 'Développé par Daniel Mengel',
      'Version loading…': 'Chargement de la version…',
      'Version': 'Version',
      'unavailable': 'indisponible',
      'Software updates': 'Mises à jour logicielles',
      'Check GitHub to see whether a newer release is available.':
          'Vérifiez sur GitHub si une version plus récente est disponible.',
      'Check for updates': 'Rechercher des mises à jour',
      'Download and install…': 'Télécharger et installer…',
      'Open GitHub release': 'Ouvrir la version GitHub',
      'Provide context or instructions for translation…':
          'Indiquez le contexte ou les instructions de traduction…',
      'Type or paste your source text here…':
          'Saisissez ou collez le texte source ici…',
      'Your translation will appear here…': 'Votre traduction apparaîtra ici…',
      'Translation style': 'Style de traduction',
      'Generate more alternatives': 'Générer plus de variantes',
      'Alternative instruction (optional)':
          'Instruction pour les variantes (facultatif)',
      'Corrected / rewritten text': 'Texte corrigé / reformulé',
      'Rewrite style': 'Style de reformulation',
      'Correct text': 'Corriger le texte',
      'OpenAI-compatible': 'Compatible OpenAI',
      'Anthropic-compatible': 'Compatible Anthropic',
      'Local OpenAI-compatible': 'Compatible OpenAI local',
    },
    'es': {
      'System default': 'Predeterminado del sistema',
      'Translate': 'Traducir',
      'Correction': 'Corrección',
      'Documents': 'Documentos',
      'Settings': 'Ajustes',
      'Direct instruction': 'Instrucción directa',
      'Translation': 'Traducción',
      'Source': 'Origen',
      'Target': 'Destino',
      'Automatic': 'Automático',
      'Copy': 'Copiar',
      'Alternatives': 'Alternativas',
      'More alternatives': 'Más alternativas',
      'Generate more': 'Generar más',
      'Suggestions for the full translation':
          'Sugerencias para toda la traducción',
      'Alternatives for the full translation':
          'Alternativas para toda la traducción',
      'Alternatives for': 'Alternativas para',
      'Auto-translate': 'Traducción automática',
      'Clear': 'Limpiar',
      'Correct': 'Corregir',
      'Rewrite': 'Reescribir',
      'General': 'General',
      'AI Providers': 'Proveedores de IA',
      'About': 'Acerca de',
      'Appearance': 'Apariencia',
      'Application language': 'Idioma de la aplicación',
      'Language': 'Idioma',
      'Theme': 'Tema',
      'System': 'Sistema',
      'Light': 'Claro',
      'Dark': 'Oscuro',
      'Save': 'Guardar',
      'Cancel': 'Cancelar',
      'Add files': 'Añadir archivos',
      'Add folder': 'Añadir carpeta',
      'Output folder': 'Carpeta de salida',
      'Process': 'Procesar',
      'Test connection': 'Probar conexión',
      'Command': 'Comando',
      'Type a command or press ⌘K': 'Escribe un comando o pulsa ⌘K',
      'Style': 'Estilo',
      'Custom': 'Personalizado',
      'Register': 'Registro',
      'Complexity': 'Complejidad',
      'Spelling': 'Ortografía',
      'Reset to defaults': 'Restablecer valores predeterminados',
      'Neutral': 'Neutro',
      'Formal': 'Formal',
      'Informal': 'Informal',
      'Technical': 'Técnico',
      'Plain': 'Sencillo',
      'Preserve': 'Conservar',
      'Fix source': 'Corregir origen',
      'Fix target': 'Corregir destino',
      'English (US)': 'Inglés (EE. UU.)',
      'English (UK)': 'Inglés (Reino Unido)',
      'German': 'Alemán',
      'French': 'Francés',
      'Spanish': 'Español',
      'Italian': 'Italiano',
      'Portuguese': 'Portugués',
      'Dutch': 'Neerlandés',
      'Polish': 'Polaco',
      'Russian': 'Ruso',
      'Japanese': 'Japonés',
      'Korean': 'Coreano',
      'Chinese Simplified': 'Chino simplificado',
      'Chinese Traditional': 'Chino tradicional',
      'Swap source and target languages':
          'Intercambiar idiomas de origen y destino',
      'Choose a fixed source language to swap languages':
          'Elige un idioma de origen fijo para intercambiar los idiomas',
      'Ready': 'Listo',
      'Translated': 'Traducido',
      'Copy translation': 'Copiar traducción',
      'Clear source and translation': 'Borrar origen y traducción',
      'Translate automatically after source changes':
          'Traducir automáticamente al cambiar el origen',
      'Manual translation only': 'Solo traducción manual',
      'Close style options': 'Cerrar opciones de estilo',
      'Correction instruction': 'Instrucción de corrección',
      'Describe how the text should be corrected or rewritten…':
          'Describe cómo debe corregirse o reescribirse el texto…',
      'Type or paste the text you want to improve…':
          'Escribe o pega el texto que quieres mejorar…',
      'characters': 'caracteres',
      'Clear input and correction': 'Borrar entrada y corrección',
      'Copy result': 'Copiar resultado',
      'The corrected or rewritten text will appear here…':
          'El texto corregido o reescrito aparecerá aquí…',
      'Concise': 'Conciso',
      'Standard': 'Estándar',
      'Ultra Short': 'Ultracorto',
      'No output folder selected': 'No se ha seleccionado carpeta de salida',
      'queued': 'en cola',
      'Optional instruction for all documents…':
          'Instrucción opcional para todos los documentos…',
      'Export': 'Exportar',
      'Processing results': 'Resultados del procesamiento',
      'Results appear here': 'Los resultados aparecen aquí',
      'Results appear here.': 'Los resultados aparecen aquí.',
      'Drop files or folders here.': 'Suelta archivos o carpetas aquí.',
      'Remove': 'Eliminar',
      'error': 'error',
      'errors': 'errores',
      'Detected local model': 'Modelo local detectado',
      'Reasoning options': 'Opciones de razonamiento',
      'Reasoning metadata unavailable':
          'Metadatos de razonamiento no disponibles',
      'Request cancelled.': 'Solicitud cancelada.',
      'Cancelling request…': 'Cancelando solicitud…',
      'CONFIGURATION': 'CONFIGURACIÓN',
      'Changes are stored locally.': 'Los cambios se guardan localmente.',
      'Choose how AbyssL looks on this device.':
          'Elige cómo se muestra AbyssL en este dispositivo.',
      'Follow the macOS language or choose an app language.':
          'Usa el idioma de macOS o elige el idioma de la aplicación.',
      'Default provider': 'Proveedor predeterminado',
      'Select the service used for new requests.':
          'Selecciona el servicio para las nuevas solicitudes.',
      'Provider': 'Proveedor',
      'Configuration': 'Configuración',
      'Edit endpoints and models under AI Providers':
          'Edita los endpoints y modelos en Proveedores de IA',
      'Editor and capture': 'Editor y captura',
      'Tune text size and the global capture shortcut.':
          'Ajusta el tamaño del texto y el atajo global de captura.',
      'Editor font size': 'Tamaño de fuente del editor',
      'Font': 'Fuente',
      'Capture modifier': 'Modificador de captura',
      'Capture key': 'Tecla de captura',
      'Base URL': 'URL base',
      'Model ID': 'ID del modelo',
      'Timeout seconds': 'Tiempo de espera en segundos',
      'Authentication': 'Autenticación',
      'API key': 'Clave API',
      'Include the API path, for example /v1.':
          'Incluye la ruta de la API, por ejemplo /v1.',
      'Bearer token': 'Token Bearer',
      'No authentication': 'Sin autenticación',
      'Stored in the operating system keychain.':
          'Guardada en el llavero del sistema operativo.',
      'Anthropic version header': 'Cabecera de versión de Anthropic',
      'Default': 'Predeterminado',
      'Available models': 'Modelos disponibles',
      'Load models': 'Cargar modelos',
      'Detect Local': 'Detectar local',
      'Reasoning': 'Razonamiento',
      'Map model-specific reasoning values.':
          'Asigna valores de razonamiento específicos del modelo.',
      'Reasoning value ON': 'Valor de razonamiento ACTIVADO',
      'Reasoning value OFF': 'Valor de razonamiento DESACTIVADO',
      'Reasoning enabled': 'Razonamiento activado',
      'Refresh': 'Actualizar',
      'None': 'Ninguno',
      'Off': 'Desactivado',
      'On': 'Activado',
      'Low': 'Bajo',
      'Medium': 'Medio',
      'High': 'Alto',
      'Connection successful.': 'Conexión correcta.',
      'About AbyssL': 'Acerca de AbyssL',
      'Application details, project website, and updates.':
          'Detalles de la aplicación, sitio del proyecto y actualizaciones.',
      'Developed by Daniel Mengel': 'Desarrollado por Daniel Mengel',
      'Version loading…': 'Cargando versión…',
      'Version': 'Versión',
      'unavailable': 'no disponible',
      'Software updates': 'Actualizaciones de software',
      'Check GitHub to see whether a newer release is available.':
          'Comprueba en GitHub si hay una versión más reciente.',
      'Check for updates': 'Buscar actualizaciones',
      'Download and install…': 'Descargar e instalar…',
      'Open GitHub release': 'Abrir versión en GitHub',
      'Provide context or instructions for translation…':
          'Indica el contexto o las instrucciones de traducción…',
      'Type or paste your source text here…':
          'Escribe o pega aquí el texto de origen…',
      'Your translation will appear here…': 'Tu traducción aparecerá aquí…',
      'Translation style': 'Estilo de traducción',
      'Generate more alternatives': 'Generar más alternativas',
      'Alternative instruction (optional)':
          'Instrucción para alternativas (opcional)',
      'Corrected / rewritten text': 'Texto corregido / reescrito',
      'Rewrite style': 'Estilo de reescritura',
      'Correct text': 'Corregir texto',
      'OpenAI-compatible': 'Compatible con OpenAI',
      'Anthropic-compatible': 'Compatible con Anthropic',
      'Local OpenAI-compatible': 'Compatible con OpenAI local',
    },
    'pt': {
      'System default': 'Padrão do sistema',
      'Translate': 'Traduzir',
      'Correction': 'Correção',
      'Documents': 'Documentos',
      'Settings': 'Definições',
      'Direct instruction': 'Instrução direta',
      'Translation': 'Tradução',
      'Source': 'Origem',
      'Target': 'Destino',
      'Automatic': 'Automático',
      'Copy': 'Copiar',
      'Alternatives': 'Alternativas',
      'More alternatives': 'Mais alternativas',
      'Generate more': 'Gerar mais',
      'Suggestions for the full translation': 'Sugestões para toda a tradução',
      'Alternatives for the full translation':
          'Alternativas para toda a tradução',
      'Alternatives for': 'Alternativas para',
      'Auto-translate': 'Tradução automática',
      'Clear': 'Limpar',
      'Correct': 'Corrigir',
      'Rewrite': 'Reescrever',
      'General': 'Geral',
      'AI Providers': 'Fornecedores de IA',
      'About': 'Sobre',
      'Appearance': 'Aspeto',
      'Application language': 'Idioma da aplicação',
      'Language': 'Idioma',
      'Theme': 'Tema',
      'System': 'Sistema',
      'Light': 'Claro',
      'Dark': 'Escuro',
      'Save': 'Guardar',
      'Cancel': 'Cancelar',
      'Process': 'Processar',
      'Test connection': 'Testar ligação',
      'Command': 'Comando',
      'Type a command or press ⌘K': 'Escreva um comando ou prima ⌘K',
      'Style': 'Estilo',
      'Custom': 'Personalizado',
      'Register': 'Registo',
      'Complexity': 'Complexidade',
      'Spelling': 'Ortografia',
      'Reset to defaults': 'Repor predefinições',
      'Neutral': 'Neutro',
      'Formal': 'Formal',
      'Informal': 'Informal',
      'Technical': 'Técnico',
      'Plain': 'Simples',
      'Preserve': 'Preservar',
      'Fix source': 'Corrigir origem',
      'Fix target': 'Corrigir destino',
      'English (US)': 'Inglês (EUA)',
      'English (UK)': 'Inglês (Reino Unido)',
      'German': 'Alemão',
      'French': 'Francês',
      'Spanish': 'Espanhol',
      'Italian': 'Italiano',
      'Portuguese': 'Português',
      'Dutch': 'Neerlandês',
      'Polish': 'Polaco',
      'Russian': 'Russo',
      'Japanese': 'Japonês',
      'Korean': 'Coreano',
      'Chinese Simplified': 'Chinês simplificado',
      'Chinese Traditional': 'Chinês tradicional',
      'Swap source and target languages': 'Trocar idiomas de origem e destino',
      'Choose a fixed source language to swap languages':
          'Escolha um idioma de origem fixo para trocar os idiomas',
      'Ready': 'Pronto',
      'Translated': 'Traduzido',
      'Copy translation': 'Copiar tradução',
      'Clear source and translation': 'Limpar origem e tradução',
      'Translate automatically after source changes':
          'Traduzir automaticamente após alterações na origem',
      'Manual translation only': 'Apenas tradução manual',
      'Close style options': 'Fechar opções de estilo',
      'Correction instruction': 'Instrução de correção',
      'Describe how the text should be corrected or rewritten…':
          'Descreva como o texto deve ser corrigido ou reescrito…',
      'Type or paste the text you want to improve…':
          'Escreva ou cole o texto que pretende melhorar…',
      'characters': 'carateres',
      'Clear input and correction': 'Limpar entrada e correção',
      'Copy result': 'Copiar resultado',
      'The corrected or rewritten text will appear here…':
          'O texto corrigido ou reescrito aparecerá aqui…',
      'Concise': 'Conciso',
      'Standard': 'Padrão',
      'Ultra Short': 'Ultracurto',
      'No output folder selected': 'Nenhuma pasta de saída selecionada',
      'queued': 'em fila',
      'Optional instruction for all documents…':
          'Instrução opcional para todos os documentos…',
      'Export': 'Exportar',
      'Processing results': 'Resultados do processamento',
      'Results appear here': 'Os resultados aparecem aqui',
      'Results appear here.': 'Os resultados aparecem aqui.',
      'Drop files or folders here.': 'Largue ficheiros ou pastas aqui.',
      'Remove': 'Remover',
      'error': 'erro',
      'errors': 'erros',
      'Detected local model': 'Modelo local detetado',
      'Reasoning options': 'Opções de raciocínio',
      'Reasoning metadata unavailable': 'Metadados de raciocínio indisponíveis',
      'Request cancelled.': 'Pedido cancelado.',
      'Cancelling request…': 'A cancelar o pedido…',
      'CONFIGURATION': 'CONFIGURAÇÃO',
      'Changes are stored locally.': 'As alterações são guardadas localmente.',
      'Choose how AbyssL looks on this device.':
          'Escolha o aspeto do AbyssL neste dispositivo.',
      'Follow the macOS language or choose an app language.':
          'Siga o idioma do macOS ou escolha o idioma da aplicação.',
      'Default provider': 'Fornecedor predefinido',
      'Select the service used for new requests.':
          'Selecione o serviço usado para novos pedidos.',
      'Provider': 'Fornecedor',
      'Configuration': 'Configuração',
      'Edit endpoints and models under AI Providers':
          'Edite endpoints e modelos em Fornecedores de IA',
      'Editor and capture': 'Editor e captura',
      'Tune text size and the global capture shortcut.':
          'Ajuste o tamanho do texto e o atalho global de captura.',
      'Editor font size': 'Tamanho da letra do editor',
      'Font': 'Letra',
      'Capture modifier': 'Modificador de captura',
      'Capture key': 'Tecla de captura',
      'Base URL': 'URL base',
      'Model ID': 'ID do modelo',
      'Timeout seconds': 'Tempo limite em segundos',
      'Authentication': 'Autenticação',
      'API key': 'Chave API',
      'Include the API path, for example /v1.':
          'Inclua o caminho da API, por exemplo /v1.',
      'Bearer token': 'Token Bearer',
      'No authentication': 'Sem autenticação',
      'Stored in the operating system keychain.':
          'Guardada no porta-chaves do sistema operativo.',
      'Anthropic version header': 'Cabeçalho de versão Anthropic',
      'Default': 'Predefinição',
      'Available models': 'Modelos disponíveis',
      'Load models': 'Carregar modelos',
      'Detect Local': 'Detetar local',
      'Reasoning': 'Raciocínio',
      'Map model-specific reasoning values.':
          'Associe valores de raciocínio específicos do modelo.',
      'Reasoning value ON': 'Valor de raciocínio LIGADO',
      'Reasoning value OFF': 'Valor de raciocínio DESLIGADO',
      'Reasoning enabled': 'Raciocínio ativado',
      'Refresh': 'Atualizar',
      'None': 'Nenhum',
      'Off': 'Desligado',
      'On': 'Ligado',
      'Low': 'Baixo',
      'Medium': 'Médio',
      'High': 'Alto',
      'Connection successful.': 'Ligação bem-sucedida.',
      'About AbyssL': 'Sobre o AbyssL',
      'Application details, project website, and updates.':
          'Detalhes da aplicação, site do projeto e atualizações.',
      'Developed by Daniel Mengel': 'Desenvolvido por Daniel Mengel',
      'Version loading…': 'A carregar versão…',
      'Version': 'Versão',
      'unavailable': 'indisponível',
      'Software updates': 'Atualizações de software',
      'Check GitHub to see whether a newer release is available.':
          'Verifique no GitHub se existe uma versão mais recente.',
      'Check for updates': 'Procurar atualizações',
      'Download and install…': 'Transferir e instalar…',
      'Open GitHub release': 'Abrir versão no GitHub',
      'Provide context or instructions for translation…':
          'Indique contexto ou instruções para a tradução…',
      'Type or paste your source text here…':
          'Escreva ou cole o texto de origem aqui…',
      'Your translation will appear here…': 'A tradução aparecerá aqui…',
      'Translation style': 'Estilo de tradução',
      'Generate more alternatives': 'Gerar mais alternativas',
      'Alternative instruction (optional)':
          'Instrução para alternativas (opcional)',
      'Corrected / rewritten text': 'Texto corrigido / reescrito',
      'Rewrite style': 'Estilo de reescrita',
      'Correct text': 'Corrigir texto',
      'Add files': 'Adicionar ficheiros',
      'Add folder': 'Adicionar pasta',
      'Output folder': 'Pasta de saída',
      'OpenAI-compatible': 'Compatível com OpenAI',
      'Anthropic-compatible': 'Compatível com Anthropic',
      'Local OpenAI-compatible': 'Compatível com OpenAI local',
    },
    'it': {
      'System default': 'Predefinito del sistema',
      'Translate': 'Traduci',
      'Correction': 'Correzione',
      'Documents': 'Documenti',
      'Settings': 'Impostazioni',
      'Direct instruction': 'Istruzione diretta',
      'Translation': 'Traduzione',
      'Source': 'Origine',
      'Target': 'Destinazione',
      'Automatic': 'Automatico',
      'Copy': 'Copia',
      'Alternatives': 'Alternative',
      'More alternatives': 'Altre alternative',
      'Generate more': 'Genera altre',
      'Suggestions for the full translation':
          'Suggerimenti per l’intera traduzione',
      'Alternatives for the full translation':
          'Alternative per l’intera traduzione',
      'Alternatives for': 'Alternative per',
      'Auto-translate': 'Traduzione automatica',
      'Clear': 'Cancella',
      'Correct': 'Correggi',
      'Rewrite': 'Riscrivi',
      'General': 'Generale',
      'AI Providers': 'Provider IA',
      'About': 'Informazioni',
      'Appearance': 'Aspetto',
      'Application language': "Lingua dell’app",
      'Language': 'Lingua',
      'Theme': 'Tema',
      'System': 'Sistema',
      'Light': 'Chiaro',
      'Dark': 'Scuro',
      'Save': 'Salva',
      'Cancel': 'Annulla',
      'Process': 'Elabora',
      'Test connection': 'Verifica connessione',
      'Command': 'Comando',
      'Type a command or press ⌘K': 'Digita un comando o premi ⌘K',
      'Style': 'Stile',
      'Custom': 'Personalizzato',
      'Register': 'Registro',
      'Complexity': 'Complessità',
      'Spelling': 'Ortografia',
      'Reset to defaults': 'Ripristina predefiniti',
      'Neutral': 'Neutro',
      'Formal': 'Formale',
      'Informal': 'Informale',
      'Technical': 'Tecnico',
      'Plain': 'Semplice',
      'Preserve': 'Mantieni',
      'Fix source': 'Correggi sorgente',
      'Fix target': 'Correggi destinazione',
      'English (US)': 'Inglese (USA)',
      'English (UK)': 'Inglese (Regno Unito)',
      'German': 'Tedesco',
      'French': 'Francese',
      'Spanish': 'Spagnolo',
      'Italian': 'Italiano',
      'Portuguese': 'Portoghese',
      'Dutch': 'Olandese',
      'Polish': 'Polacco',
      'Russian': 'Russo',
      'Japanese': 'Giapponese',
      'Korean': 'Coreano',
      'Chinese Simplified': 'Cinese semplificato',
      'Chinese Traditional': 'Cinese tradizionale',
      'Swap source and target languages':
          'Scambia lingue di origine e destinazione',
      'Choose a fixed source language to swap languages':
          'Scegli una lingua di origine fissa per scambiare le lingue',
      'Ready': 'Pronto',
      'Translated': 'Tradotto',
      'Copy translation': 'Copia traduzione',
      'Clear source and translation': 'Cancella origine e traduzione',
      'Translate automatically after source changes':
          'Traduci automaticamente dopo le modifiche al testo sorgente',
      'Manual translation only': 'Solo traduzione manuale',
      'Close style options': 'Chiudi opzioni di stile',
      'Correction instruction': 'Istruzione di correzione',
      'Describe how the text should be corrected or rewritten…':
          'Descrivi come correggere o riscrivere il testo…',
      'Type or paste the text you want to improve…':
          'Digita o incolla il testo da migliorare…',
      'characters': 'caratteri',
      'Clear input and correction': 'Cancella input e correzione',
      'Copy result': 'Copia risultato',
      'The corrected or rewritten text will appear here…':
          'Il testo corretto o riscritto apparirà qui…',
      'Concise': 'Conciso',
      'Standard': 'Standard',
      'Ultra Short': 'Ultrabreve',
      'No output folder selected': 'Nessuna cartella di output selezionata',
      'queued': 'in coda',
      'Optional instruction for all documents…':
          'Istruzione facoltativa per tutti i documenti…',
      'Export': 'Esporta',
      'Processing results': 'Risultati elaborazione',
      'Results appear here': 'I risultati appariranno qui',
      'Results appear here.': 'I risultati appariranno qui.',
      'Drop files or folders here.': 'Trascina qui file o cartelle.',
      'Remove': 'Rimuovi',
      'error': 'errore',
      'errors': 'errori',
      'Detected local model': 'Modello locale rilevato',
      'Reasoning options': 'Opzioni di ragionamento',
      'Reasoning metadata unavailable':
          'Metadati di ragionamento non disponibili',
      'Request cancelled.': 'Richiesta annullata.',
      'Cancelling request…': 'Annullamento richiesta…',
      'CONFIGURATION': 'CONFIGURAZIONE',
      'Changes are stored locally.': 'Le modifiche vengono salvate localmente.',
      'Choose how AbyssL looks on this device.':
          'Scegli l’aspetto di AbyssL su questo dispositivo.',
      'Follow the macOS language or choose an app language.':
          'Usa la lingua di macOS o scegli la lingua dell’app.',
      'Default provider': 'Provider predefinito',
      'Select the service used for new requests.':
          'Seleziona il servizio per le nuove richieste.',
      'Provider': 'Provider',
      'Configuration': 'Configurazione',
      'Edit endpoints and models under AI Providers':
          'Modifica endpoint e modelli in Provider IA',
      'Editor and capture': 'Editor e acquisizione',
      'Tune text size and the global capture shortcut.':
          'Regola dimensione del testo e scorciatoia globale di acquisizione.',
      'Editor font size': 'Dimensione carattere editor',
      'Font': 'Carattere',
      'Capture modifier': 'Modificatore acquisizione',
      'Capture key': 'Tasto acquisizione',
      'Base URL': 'URL di base',
      'Model ID': 'ID modello',
      'Timeout seconds': 'Timeout in secondi',
      'Authentication': 'Autenticazione',
      'API key': 'Chiave API',
      'Include the API path, for example /v1.':
          'Includi il percorso API, ad esempio /v1.',
      'Bearer token': 'Token Bearer',
      'No authentication': 'Nessuna autenticazione',
      'Stored in the operating system keychain.':
          'Salvata nel portachiavi del sistema operativo.',
      'Anthropic version header': 'Header versione Anthropic',
      'Default': 'Predefinito',
      'Available models': 'Modelli disponibili',
      'Load models': 'Carica modelli',
      'Detect Local': 'Rileva locale',
      'Reasoning': 'Ragionamento',
      'Map model-specific reasoning values.':
          'Associa i valori di ragionamento specifici del modello.',
      'Reasoning value ON': 'Valore ragionamento ATTIVO',
      'Reasoning value OFF': 'Valore ragionamento DISATTIVO',
      'Reasoning enabled': 'Ragionamento attivo',
      'Refresh': 'Aggiorna',
      'None': 'Nessuno',
      'Off': 'Disattivo',
      'On': 'Attivo',
      'Low': 'Basso',
      'Medium': 'Medio',
      'High': 'Alto',
      'Connection successful.': 'Connessione riuscita.',
      'About AbyssL': 'Informazioni su AbyssL',
      'Application details, project website, and updates.':
          'Dettagli dell’app, sito del progetto e aggiornamenti.',
      'Developed by Daniel Mengel': 'Sviluppato da Daniel Mengel',
      'Version loading…': 'Caricamento versione…',
      'Version': 'Versione',
      'unavailable': 'non disponibile',
      'Software updates': 'Aggiornamenti software',
      'Check GitHub to see whether a newer release is available.':
          'Controlla su GitHub se è disponibile una versione più recente.',
      'Check for updates': 'Controlla aggiornamenti',
      'Download and install…': 'Scarica e installa…',
      'Open GitHub release': 'Apri release GitHub',
      'Provide context or instructions for translation…':
          'Fornisci contesto o istruzioni per la traduzione…',
      'Type or paste your source text here…':
          'Digita o incolla qui il testo sorgente…',
      'Your translation will appear here…': 'La traduzione apparirà qui…',
      'Translation style': 'Stile di traduzione',
      'Generate more alternatives': 'Genera altre alternative',
      'Alternative instruction (optional)':
          'Istruzione per le alternative (facoltativa)',
      'Corrected / rewritten text': 'Testo corretto / riscritto',
      'Rewrite style': 'Stile di riscrittura',
      'Correct text': 'Correggi testo',
      'Add files': 'Aggiungi file',
      'Add folder': 'Aggiungi cartella',
      'Output folder': 'Cartella di output',
      'OpenAI-compatible': 'Compatibile OpenAI',
      'Anthropic-compatible': 'Compatibile Anthropic',
      'Local OpenAI-compatible': 'Compatibile OpenAI locale',
    },
    'nl': {
      'System default': 'Systeemstandaard',
      'Translate': 'Vertalen',
      'Correction': 'Correctie',
      'Documents': 'Documenten',
      'Settings': 'Instellingen',
      'Direct instruction': 'Directe instructie',
      'Translation': 'Vertaling',
      'Source': 'Bron',
      'Target': 'Doel',
      'Automatic': 'Automatisch',
      'Copy': 'Kopiëren',
      'Alternatives': 'Alternatieven',
      'More alternatives': 'Meer alternatieven',
      'Generate more': 'Meer genereren',
      'Suggestions for the full translation':
          'Suggesties voor de hele vertaling',
      'Alternatives for the full translation':
          'Alternatieven voor de hele vertaling',
      'Alternatives for': 'Alternatieven voor',
      'Auto-translate': 'Automatisch vertalen',
      'Clear': 'Wissen',
      'Correct': 'Corrigeren',
      'Rewrite': 'Herschrijven',
      'General': 'Algemeen',
      'AI Providers': 'AI-providers',
      'About': 'Over',
      'Appearance': 'Weergave',
      'Application language': 'App-taal',
      'Language': 'Taal',
      'Theme': 'Thema',
      'System': 'Systeem',
      'Light': 'Licht',
      'Dark': 'Donker',
      'Save': 'Opslaan',
      'Cancel': 'Annuleren',
      'Process': 'Verwerken',
      'Test connection': 'Verbinding testen',
      'Command': 'Opdracht',
      'Type a command or press ⌘K': 'Typ een opdracht of druk op ⌘K',
      'Style': 'Stijl',
      'Custom': 'Aangepast',
      'Register': 'Register',
      'Complexity': 'Complexiteit',
      'Spelling': 'Spelling',
      'Reset to defaults': 'Standaardwaarden herstellen',
      'Neutral': 'Neutraal',
      'Formal': 'Formeel',
      'Informal': 'Informeel',
      'Technical': 'Technisch',
      'Plain': 'Eenvoudig',
      'Preserve': 'Behouden',
      'Fix source': 'Bron corrigeren',
      'Fix target': 'Doel corrigeren',
      'English (US)': 'Engels (VS)',
      'English (UK)': 'Engels (VK)',
      'German': 'Duits',
      'French': 'Frans',
      'Spanish': 'Spaans',
      'Italian': 'Italiaans',
      'Portuguese': 'Portugees',
      'Dutch': 'Nederlands',
      'Polish': 'Pools',
      'Russian': 'Russisch',
      'Japanese': 'Japans',
      'Korean': 'Koreaans',
      'Chinese Simplified': 'Vereenvoudigd Chinees',
      'Chinese Traditional': 'Traditioneel Chinees',
      'Swap source and target languages': 'Bron- en doeltaal wisselen',
      'Choose a fixed source language to swap languages':
          'Kies een vaste brontaal om talen te wisselen',
      'Ready': 'Gereed',
      'Translated': 'Vertaald',
      'Copy translation': 'Vertaling kopiëren',
      'Clear source and translation': 'Bron en vertaling wissen',
      'Translate automatically after source changes':
          'Automatisch vertalen na wijzigingen in de bron',
      'Manual translation only': 'Alleen handmatig vertalen',
      'Close style options': 'Stijlopties sluiten',
      'Correction instruction': 'Correctie-instructie',
      'Describe how the text should be corrected or rewritten…':
          'Beschrijf hoe de tekst moet worden gecorrigeerd of herschreven…',
      'Type or paste the text you want to improve…':
          'Typ of plak de tekst die je wilt verbeteren…',
      'characters': 'tekens',
      'Clear input and correction': 'Invoer en correctie wissen',
      'Copy result': 'Resultaat kopiëren',
      'The corrected or rewritten text will appear here…':
          'De gecorrigeerde of herschreven tekst verschijnt hier…',
      'Concise': 'Beknopt',
      'Standard': 'Standaard',
      'Ultra Short': 'Ultrakort',
      'No output folder selected': 'Geen uitvoermap geselecteerd',
      'queued': 'in wachtrij',
      'Optional instruction for all documents…':
          'Optionele instructie voor alle documenten…',
      'Export': 'Exporteren',
      'Processing results': 'Verwerkingsresultaten',
      'Results appear here': 'Resultaten verschijnen hier',
      'Results appear here.': 'Resultaten verschijnen hier.',
      'Drop files or folders here.': 'Sleep bestanden of mappen hierheen.',
      'Remove': 'Verwijderen',
      'error': 'fout',
      'errors': 'fouten',
      'Detected local model': 'Lokaal model gedetecteerd',
      'Reasoning options': 'Redeneeropties',
      'Reasoning metadata unavailable': 'Redeneermetadata niet beschikbaar',
      'Request cancelled.': 'Verzoek geannuleerd.',
      'Cancelling request…': 'Verzoek annuleren…',
      'CONFIGURATION': 'CONFIGURATIE',
      'Changes are stored locally.': 'Wijzigingen worden lokaal opgeslagen.',
      'Choose how AbyssL looks on this device.':
          'Kies hoe AbyssL er op dit apparaat uitziet.',
      'Follow the macOS language or choose an app language.':
          'Volg de macOS-taal of kies een app-taal.',
      'Default provider': 'Standaardprovider',
      'Select the service used for new requests.':
          'Selecteer de dienst voor nieuwe verzoeken.',
      'Provider': 'Provider',
      'Configuration': 'Configuratie',
      'Edit endpoints and models under AI Providers':
          'Bewerk eindpunten en modellen onder AI-providers',
      'Editor and capture': 'Editor en vastleggen',
      'Tune text size and the global capture shortcut.':
          'Pas tekstgrootte en de algemene sneltoets aan.',
      'Editor font size': 'Lettergrootte editor',
      'Font': 'Lettertype',
      'Capture modifier': 'Modificatietoets vastleggen',
      'Capture key': 'Toets vastleggen',
      'Base URL': 'Basis-URL',
      'Model ID': 'Model-ID',
      'Timeout seconds': 'Time-out in seconden',
      'Authentication': 'Authenticatie',
      'API key': 'API-sleutel',
      'Include the API path, for example /v1.':
          'Neem het API-pad op, bijvoorbeeld /v1.',
      'Bearer token': 'Bearer-token',
      'No authentication': 'Geen authenticatie',
      'Stored in the operating system keychain.':
          'Opgeslagen in de sleutelhanger van het besturingssysteem.',
      'Anthropic version header': 'Anthropic-versieheader',
      'Default': 'Standaard',
      'Available models': 'Beschikbare modellen',
      'Load models': 'Modellen laden',
      'Detect Local': 'Lokaal detecteren',
      'Reasoning': 'Redeneren',
      'Map model-specific reasoning values.':
          'Koppel modelspecifieke redeneerwaarden.',
      'Reasoning value ON': 'Redeneerwaarde AAN',
      'Reasoning value OFF': 'Redeneerwaarde UIT',
      'Reasoning enabled': 'Redeneren ingeschakeld',
      'Refresh': 'Vernieuwen',
      'None': 'Geen',
      'Off': 'Uit',
      'On': 'Aan',
      'Low': 'Laag',
      'Medium': 'Gemiddeld',
      'High': 'Hoog',
      'Connection successful.': 'Verbinding geslaagd.',
      'About AbyssL': 'Over AbyssL',
      'Application details, project website, and updates.':
          'App-details, projectwebsite en updates.',
      'Developed by Daniel Mengel': 'Ontwikkeld door Daniel Mengel',
      'Version loading…': 'Versie laden…',
      'Version': 'Versie',
      'unavailable': 'niet beschikbaar',
      'Software updates': 'Software-updates',
      'Check GitHub to see whether a newer release is available.':
          'Controleer op GitHub of er een nieuwere versie is.',
      'Check for updates': 'Controleren op updates',
      'Download and install…': 'Downloaden en installeren…',
      'Open GitHub release': 'GitHub-release openen',
      'Provide context or instructions for translation…':
          'Geef context of instructies voor de vertaling…',
      'Type or paste your source text here…': 'Typ of plak hier de brontekst…',
      'Your translation will appear here…': 'Je vertaling verschijnt hier…',
      'Translation style': 'Vertaalstijl',
      'Generate more alternatives': 'Meer alternatieven genereren',
      'Alternative instruction (optional)':
          'Instructie voor alternatieven (optioneel)',
      'Corrected / rewritten text': 'Gecorrigeerde / herschreven tekst',
      'Rewrite style': 'Herschrijfstijl',
      'Correct text': 'Tekst corrigeren',
      'Add files': 'Bestanden toevoegen',
      'Add folder': 'Map toevoegen',
      'Output folder': 'Uitvoermap',
      'OpenAI-compatible': 'OpenAI-compatibel',
      'Anthropic-compatible': 'Anthropic-compatibel',
      'Local OpenAI-compatible': 'Lokaal OpenAI-compatibel',
    },
    'hr': {
      'System default': 'Zadano sustavom',
      'Translate': 'Prevedi',
      'Correction': 'Ispravak',
      'Documents': 'Dokumenti',
      'Settings': 'Postavke',
      'Direct instruction': 'Izravna uputa',
      'Translation': 'Prijevod',
      'Source': 'Izvor',
      'Target': 'Cilj',
      'Automatic': 'Automatski',
      'Copy': 'Kopiraj',
      'Alternatives': 'Alternative',
      'More alternatives': 'Više alternativa',
      'Generate more': 'Generiraj više',
      'Suggestions for the full translation': 'Prijedlozi za cijeli prijevod',
      'Alternatives for the full translation': 'Alternative za cijeli prijevod',
      'Alternatives for': 'Alternative za',
      'Auto-translate': 'Automatski prevedi',
      'Clear': 'Očisti',
      'Correct': 'Ispravi',
      'Rewrite': 'Prepiši',
      'General': 'Općenito',
      'AI Providers': 'Pružatelji UI-a',
      'About': 'O aplikaciji',
      'Appearance': 'Izgled',
      'Application language': 'Jezik aplikacije',
      'Language': 'Jezik',
      'Theme': 'Tema',
      'System': 'Sustav',
      'Light': 'Svijetlo',
      'Dark': 'Tamno',
      'Save': 'Spremi',
      'Cancel': 'Odustani',
      'Process': 'Obradi',
      'Test connection': 'Testiraj vezu',
      'Command': 'Naredba',
      'Type a command or press ⌘K': 'Upišite naredbu ili pritisnite ⌘K',
      'Style': 'Stil',
      'Custom': 'Prilagođeno',
      'Register': 'Registar',
      'Complexity': 'Složenost',
      'Spelling': 'Pravopis',
      'Reset to defaults': 'Vrati zadane vrijednosti',
      'Neutral': 'Neutralno',
      'Formal': 'Formalno',
      'Informal': 'Neformalno',
      'Technical': 'Tehnički',
      'Plain': 'Jednostavno',
      'Preserve': 'Sačuvaj',
      'Fix source': 'Ispravi izvor',
      'Fix target': 'Ispravi cilj',
      'English (US)': 'Engleski (SAD)',
      'English (UK)': 'Engleski (UK)',
      'German': 'Njemački',
      'French': 'Francuski',
      'Spanish': 'Španjolski',
      'Italian': 'Talijanski',
      'Portuguese': 'Portugalski',
      'Dutch': 'Nizozemski',
      'Polish': 'Poljski',
      'Russian': 'Ruski',
      'Japanese': 'Japanski',
      'Korean': 'Korejski',
      'Chinese Simplified': 'Pojednostavljeni kineski',
      'Chinese Traditional': 'Tradicionalni kineski',
      'Swap source and target languages': 'Zamijeni izvorni i ciljni jezik',
      'Choose a fixed source language to swap languages':
          'Odaberite fiksni izvorni jezik za zamjenu jezika',
      'Ready': 'Spremno',
      'Translated': 'Prevedeno',
      'Copy translation': 'Kopiraj prijevod',
      'Clear source and translation': 'Očisti izvor i prijevod',
      'Translate automatically after source changes':
          'Automatski prevedi nakon promjene izvora',
      'Manual translation only': 'Samo ručno prevođenje',
      'Close style options': 'Zatvori mogućnosti stila',
      'Correction instruction': 'Uputa za ispravak',
      'Describe how the text should be corrected or rewritten…':
          'Opišite kako tekst treba ispraviti ili preoblikovati…',
      'Type or paste the text you want to improve…':
          'Upišite ili zalijepite tekst koji želite poboljšati…',
      'characters': 'znakova',
      'Clear input and correction': 'Očisti unos i ispravak',
      'Copy result': 'Kopiraj rezultat',
      'The corrected or rewritten text will appear here…':
          'Ispravljeni ili preoblikovani tekst pojavit će se ovdje…',
      'Concise': 'Sažeto',
      'Standard': 'Standardno',
      'Ultra Short': 'Vrlo kratko',
      'No output folder selected': 'Nije odabrana izlazna mapa',
      'queued': 'u redu čekanja',
      'Optional instruction for all documents…':
          'Neobavezna uputa za sve dokumente…',
      'Export': 'Izvoz',
      'Processing results': 'Rezultati obrade',
      'Results appear here': 'Rezultati će se pojaviti ovdje',
      'Results appear here.': 'Rezultati će se pojaviti ovdje.',
      'Drop files or folders here.': 'Ispustite datoteke ili mape ovdje.',
      'Remove': 'Ukloni',
      'error': 'pogreška',
      'errors': 'pogrešaka',
      'Detected local model': 'Otkriven lokalni model',
      'Reasoning options': 'Mogućnosti zaključivanja',
      'Reasoning metadata unavailable':
          'Metapodaci zaključivanja nisu dostupni',
      'Request cancelled.': 'Zahtjev je otkazan.',
      'Cancelling request…': 'Otkazivanje zahtjeva…',
      'CONFIGURATION': 'KONFIGURACIJA',
      'Changes are stored locally.': 'Promjene se spremaju lokalno.',
      'Choose how AbyssL looks on this device.':
          'Odaberite izgled AbyssL-a na ovom uređaju.',
      'Follow the macOS language or choose an app language.':
          'Pratite jezik macOS-a ili odaberite jezik aplikacije.',
      'Default provider': 'Zadani pružatelj',
      'Select the service used for new requests.':
          'Odaberite uslugu za nove zahtjeve.',
      'Provider': 'Pružatelj',
      'Configuration': 'Konfiguracija',
      'Edit endpoints and models under AI Providers':
          'Uredite krajnje točke i modele pod Pružatelji UI-a',
      'Editor and capture': 'Uređivač i snimanje',
      'Tune text size and the global capture shortcut.':
          'Prilagodite veličinu teksta i globalni prečac za snimanje.',
      'Editor font size': 'Veličina fonta uređivača',
      'Font': 'Font',
      'Capture modifier': 'Modifikator snimanja',
      'Capture key': 'Tipka za snimanje',
      'Base URL': 'Osnovni URL',
      'Model ID': 'ID modela',
      'Timeout seconds': 'Istek vremena u sekundama',
      'Authentication': 'Autentifikacija',
      'API key': 'API ključ',
      'Include the API path, for example /v1.':
          'Uključite API putanju, primjerice /v1.',
      'Bearer token': 'Bearer token',
      'No authentication': 'Bez autentifikacije',
      'Stored in the operating system keychain.':
          'Spremljeno u privjesku ključeva operacijskog sustava.',
      'Anthropic version header': 'Zaglavlje verzije Anthropic',
      'Default': 'Zadano',
      'Available models': 'Dostupni modeli',
      'Load models': 'Učitaj modele',
      'Detect Local': 'Otkrij lokalno',
      'Reasoning': 'Zaključivanje',
      'Map model-specific reasoning values.':
          'Povežite vrijednosti zaključivanja specifične za model.',
      'Reasoning value ON': 'Vrijednost zaključivanja UKLJUČENO',
      'Reasoning value OFF': 'Vrijednost zaključivanja ISKLJUČENO',
      'Reasoning enabled': 'Zaključivanje omogućeno',
      'Refresh': 'Osvježi',
      'None': 'Nijedno',
      'Off': 'Isključeno',
      'On': 'Uključeno',
      'Low': 'Nisko',
      'Medium': 'Srednje',
      'High': 'Visoko',
      'Connection successful.': 'Veza je uspješna.',
      'About AbyssL': 'O aplikaciji AbyssL',
      'Application details, project website, and updates.':
          'Podaci o aplikaciji, mrežno mjesto projekta i ažuriranja.',
      'Developed by Daniel Mengel': 'Razvio Daniel Mengel',
      'Version loading…': 'Učitavanje verzije…',
      'Version': 'Verzija',
      'unavailable': 'nije dostupno',
      'Software updates': 'Ažuriranja softvera',
      'Check GitHub to see whether a newer release is available.':
          'Provjerite na GitHubu postoji li novija verzija.',
      'Check for updates': 'Provjeri ažuriranja',
      'Download and install…': 'Preuzmi i instaliraj…',
      'Open GitHub release': 'Otvori GitHub izdanje',
      'Provide context or instructions for translation…':
          'Navedite kontekst ili upute za prijevod…',
      'Type or paste your source text here…':
          'Ovdje upišite ili zalijepite izvorni tekst…',
      'Your translation will appear here…': 'Prijevod će se pojaviti ovdje…',
      'Translation style': 'Stil prijevoda',
      'Generate more alternatives': 'Generiraj više alternativa',
      'Alternative instruction (optional)': 'Uputa za alternative (neobavezno)',
      'Corrected / rewritten text': 'Ispravljeni / preoblikovani tekst',
      'Rewrite style': 'Stil preoblikovanja',
      'Correct text': 'Ispravi tekst',
      'Add files': 'Dodaj datoteke',
      'Add folder': 'Dodaj mapu',
      'Output folder': 'Izlazna mapa',
      'OpenAI-compatible': 'OpenAI kompatibilno',
      'Anthropic-compatible': 'Anthropic kompatibilno',
      'Local OpenAI-compatible': 'Lokalno OpenAI kompatibilno',
    },
  };
}

class _AbyssLAppLocalizationsDelegate
    extends LocalizationsDelegate<AbyssLAppLocalizations> {
  const _AbyssLAppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AbyssLAppLocalizations.supportedLocales
      .any((supported) => supported.languageCode == locale.languageCode);

  @override
  Future<AbyssLAppLocalizations> load(Locale locale) =>
      SynchronousFuture(AbyssLAppLocalizations(locale));

  @override
  bool shouldReload(_AbyssLAppLocalizationsDelegate old) => false;
}
